# Generated by Django 3.0.1 on 2019-12-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technique_name', models.CharField(max_length=200)),
                ('Technique_content', models.TextField()),
            ],
        ),
    ]
