# Generated by Django 3.0.3 on 2020-02-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_token',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
