# Generated by Django 3.0.3 on 2020-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path_to_file', models.CharField(max_length=250)),
                ('user_token', models.CharField(max_length=200)),
            ],
        ),
    ]
