# Generated by Django 3.0.3 on 2020-02-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='myfile',
        ),
    ]
